// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtobusumNerede.Api.Data;

#nullable disable

namespace OtobusumNerede.Api.Migrations
{
    [DbContext(typeof(OtobusumNeredeDbContext))]
    [Migration("20250211123052_mig2")]
    partial class mig2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OtobusumNerede.Api.Data.Entities.Durak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AkilliMi")
                        .HasColumnType("bit");

                    b.Property<double>("Boylam")
                        .HasColumnType("float");

                    b.Property<int>("DurakKodu")
                        .HasColumnType("int");

                    b.Property<bool>("EngelliKullaniminaUygunMu")
                        .HasColumnType("bit");

                    b.Property<double>("Enlem")
                        .HasColumnType("float");

                    b.Property<string>("IlceAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Duraklar");
                });

            modelBuilder.Entity("OtobusumNerede.Api.Data.Entities.GeoJson.OtobusRotasi", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int?>("B_NOKTASI")
                        .HasColumnType("int");

                    b.Property<int?>("DEPAR_NO")
                        .HasColumnType("int");

                    b.Property<string>("DURUM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUZERGAH_A")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUZERGAH_K")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HAT_ADI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HAT_BASI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HAT_ID")
                        .HasColumnType("int");

                    b.Property<string>("HAT_KODU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HAT_SONU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RING_MI")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RouteGeometry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("SURE")
                        .HasColumnType("float");

                    b.Property<double?>("UZUNLUK")
                        .HasColumnType("float");

                    b.Property<string>("YON")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("OtobusRotalari");
                });

            modelBuilder.Entity("OtobusumNerede.Api.Data.Entities.Hat", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HatAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hatlar");
                });
#pragma warning restore 612, 618
        }
    }
}
