using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.ServiceModel.Description;
using System.Xml;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuyurularServices
{
    
    
    [GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [ServiceContractAttribute(ConfigurationName="DuyurularServices.DuyurularSoap")]
    public interface DuyurularSoap
    {
        
        [OperationContractAttribute(Action="http://tempuri.org/GetDuyurular_XML", ReplyAction="*")]
        Task<GetDuyurular_XMLResponse> GetDuyurular_XMLAsync(GetDuyurular_XMLRequest request);
        
        [OperationContractAttribute(Action="http://tempuri.org/GetDuyurular_json", ReplyAction="*")]
        Task<GetDuyurular_jsonResponse> GetDuyurular_jsonAsync(GetDuyurular_jsonRequest request);
    }
    
    [DebuggerStepThroughAttribute()]
    [GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
    [MessageContractAttribute(IsWrapped=false)]
    public partial class GetDuyurular_XMLRequest
    {
        
        [MessageBodyMemberAttribute(Name="GetDuyurular_XML", Namespace="http://tempuri.org/", Order=0)]
        public GetDuyurular_XMLRequestBody Body;
        
        public GetDuyurular_XMLRequest()
        {
        }
        
        public GetDuyurular_XMLRequest(GetDuyurular_XMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [DebuggerStepThroughAttribute()]
    [GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
    [DataContractAttribute()]
    public partial class GetDuyurular_XMLRequestBody
    {
        
        public GetDuyurular_XMLRequestBody()
        {
        }
    }
    
    [DebuggerStepThroughAttribute()]
    [GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
    [MessageContractAttribute(IsWrapped=false)]
    public partial class GetDuyurular_XMLResponse
    {
        
        [MessageBodyMemberAttribute(Name="GetDuyurular_XMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetDuyurular_XMLResponseBody Body;
        
        public GetDuyurular_XMLResponse()
        {
        }
        
        public GetDuyurular_XMLResponse(GetDuyurular_XMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [DebuggerStepThroughAttribute()]
    [GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
    [DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDuyurular_XMLResponseBody
    {
        
        [DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public XmlElement GetDuyurular_XMLResult;
        
        public GetDuyurular_XMLResponseBody()
        {
        }
        
        public GetDuyurular_XMLResponseBody(XmlElement GetDuyurular_XMLResult)
        {
            this.GetDuyurular_XMLResult = GetDuyurular_XMLResult;
        }
    }
    
    [DebuggerStepThroughAttribute()]
    [GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
    [MessageContractAttribute(IsWrapped=false)]
    public partial class GetDuyurular_jsonRequest
    {
        
        [MessageBodyMemberAttribute(Name="GetDuyurular_json", Namespace="http://tempuri.org/", Order=0)]
        public GetDuyurular_jsonRequestBody Body;
        
        public GetDuyurular_jsonRequest()
        {
        }
        
        public GetDuyurular_jsonRequest(GetDuyurular_jsonRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [DebuggerStepThroughAttribute()]
    [GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
    [DataContractAttribute()]
    public partial class GetDuyurular_jsonRequestBody
    {
        
        public GetDuyurular_jsonRequestBody()
        {
        }
    }
    
    [DebuggerStepThroughAttribute()]
    [GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
    [MessageContractAttribute(IsWrapped=false)]
    public partial class GetDuyurular_jsonResponse
    {
        
        [MessageBodyMemberAttribute(Name="GetDuyurular_jsonResponse", Namespace="http://tempuri.org/", Order=0)]
        public GetDuyurular_jsonResponseBody Body;
        
        public GetDuyurular_jsonResponse()
        {
        }
        
        public GetDuyurular_jsonResponse(GetDuyurular_jsonResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [DebuggerStepThroughAttribute()]
    [GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
    [DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDuyurular_jsonResponseBody
    {
        
        [DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDuyurular_jsonResult;
        
        public GetDuyurular_jsonResponseBody()
        {
        }
        
        public GetDuyurular_jsonResponseBody(string GetDuyurular_jsonResult)
        {
            this.GetDuyurular_jsonResult = GetDuyurular_jsonResult;
        }
    }
    
    [GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface DuyurularSoapChannel : DuyurularSoap,IClientChannel
    {
    }
    
    [DebuggerStepThroughAttribute()]
    [GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class DuyurularSoapClient : ClientBase<DuyurularSoap>, DuyurularSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(ServiceEndpoint serviceEndpoint, ClientCredentials clientCredentials);
        
        public DuyurularSoapClient() : 
                base(DuyurularSoapClient.GetDefaultBinding(), DuyurularSoapClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DuyurularSoap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DuyurularSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DuyurularSoapClient.GetBindingForEndpoint(endpointConfiguration), DuyurularSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DuyurularSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DuyurularSoapClient.GetBindingForEndpoint(endpointConfiguration), new EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DuyurularSoapClient(EndpointConfiguration endpointConfiguration, EndpointAddress remoteAddress) : 
                base(DuyurularSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DuyurularSoapClient(Binding binding, EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        Task<GetDuyurular_XMLResponse> DuyurularSoap.GetDuyurular_XMLAsync(GetDuyurular_XMLRequest request)
        {
            return base.Channel.GetDuyurular_XMLAsync(request);
        }
        
        public Task<GetDuyurular_XMLResponse> GetDuyurular_XMLAsync()
        {
            GetDuyurular_XMLRequest inValue = new GetDuyurular_XMLRequest();
            inValue.Body = new GetDuyurular_XMLRequestBody();
            return ((DuyurularSoap)(this)).GetDuyurular_XMLAsync(inValue);
        }
        
        [EditorBrowsableAttribute(EditorBrowsableState.Advanced)]
        Task<GetDuyurular_jsonResponse> DuyurularSoap.GetDuyurular_jsonAsync(GetDuyurular_jsonRequest request)
        {
            return base.Channel.GetDuyurular_jsonAsync(request);
        }
        
        public Task<GetDuyurular_jsonResponse> GetDuyurular_jsonAsync()
        {
            GetDuyurular_jsonRequest inValue = new GetDuyurular_jsonRequest();
            inValue.Body = new GetDuyurular_jsonRequestBody();
            return ((DuyurularSoap)(this)).GetDuyurular_jsonAsync(inValue);
        }
        
        public virtual Task OpenAsync()
        {
            return Task.Factory.FromAsync(((ICommunicationObject)(this)).BeginOpen(null, null), new Action<IAsyncResult>(((ICommunicationObject)(this)).EndOpen));
        }
        
        private static Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DuyurularSoap))
            {
                BasicHttpBinding result = new BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DuyurularSoap))
            {
                return new EndpointAddress("https://api.ibb.gov.tr/iett/UlasimDinamikVeri/Duyurular.asmx");
            }
            throw new InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static Binding GetDefaultBinding()
        {
            return DuyurularSoapClient.GetBindingForEndpoint(EndpointConfiguration.DuyurularSoap);
        }
        
        private static EndpointAddress GetDefaultEndpointAddress()
        {
            return DuyurularSoapClient.GetEndpointAddress(EndpointConfiguration.DuyurularSoap);
        }
        
        public enum EndpointConfiguration
        {            
            DuyurularSoap,
        }
    }
}
